plugins {
    id 'com.android.application'
}

android {
    namespace 'com.bl4zers.gbzombie'
    compileSdk 36

    defaultConfig {
        applicationId 'com.bl4zers.gbzombie'
        minSdk 26
        targetSdk 36
        versionCode 120
        versionName '1.2.0'
    }

    buildTypes {
        debug {
            applicationIdSuffix '.debug'
            versionNameSuffix '-debug'
        }
        release {
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
